# Generated by Django 5.2.7 on 2025-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
